import type { Metadata } from "next";
import "@/app/globals.css";
import { ReactNode } from "react";
import CartDrawer from "@/components/CartDrawer";
import CartSyncProvider from "@/providers/CartSyncProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <CartSyncProvider>
          {children}
          <CartDrawer />
        </CartSyncProvider>
      </body>
    </html>
  );
}
